# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration, max_jerk]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# The default config of moveit does not take into account the jerk limits, the RuckigTrajectorySmoothing adapter must be
# added to the planning pipeline to support jerk limits # TODO: check if jerk dimensions are ok!!

# Easiest way to slow down the robot is to decrease the velocity and acceleration scaling factors
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  rail_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 0.1
    has_jerk: false
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.490656
    has_acceleration_limits: true
    max_acceleration: 7.505672
    has_jerk: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.994851
    has_acceleration_limits: true
    max_acceleration: 1.350277
    has_jerk: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.31613
    has_acceleration_limits: true
    max_acceleration: 13.412379
    has_jerk: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.50492
    has_acceleration_limits: true
    max_acceleration: 99.514484
    has_jerk: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 7.50492
    has_acceleration_limits: true
    max_acceleration: 95.957307
    has_jerk: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.99557
    has_acceleration_limits: true
    max_acceleration: 120.049850
    has_jerk: false
