controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    gpio_controller:
      type: gpio_controllers/GpioCommandController
    event_broadcaster:
      type: kuka_controllers/EventBroadcaster
