effort_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    gains:
      joint_1:
        p: 5.0
        i: 0.0
        d: 0.1
      joint_2:
        p: 5.0
        i: 0.0
        d: 0.1
      joint_3:
        p: 5.0
        i: 0.0
        d: 0.1
      joint_4:
        p: 5.0
        i: 0.0
        d: 0.1
      joint_5:
        p: 5.0
        i: 0.0
        d: 0.1
      joint_6:
        p: 5.0
        i: 0.0
        d: 0.1
      joint_7:
        p: 5.0
        i: 0.0
        d: 0.1
